version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/jenkins.yaml"
    volumes:
      - "./jenkins/shared-lib:/tmp/shared-lib"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
